// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Olga Goulko

#include "interactions.hpp"
#include "utilities.hpp"

#include <cmath>
#include <stdexcept>
#include <utility>
#include <vector>

using namespace std;

//grid geometry

int xcoord(int gridPoint)
    {
    return gridPoint%gridSize;
    }

int ycoord(int gridPoint)
    {
    return gridPoint/gridSize;
    }

pair<double,double> findPosition(int gridPoint)
	{
    int y = gridPoint/gridSize;
    int x = gridPoint-y*gridSize;

	pair<double,double> thisPair(x*cellSize,y*cellSize);

	return thisPair;
	}

double euclideanDistance(pair<double,double> point1, pair<double,double> point2)
	{
	double x0=point1.first-point2.first; x0=x0*x0;
	double x1=point1.second-point2.second; x1=x1*x1;
	return sqrt(x1+x0);
	}

double euclideanDistance(pair<int,int> point1, pair<int,int> point2)
	{
	double x0=point1.first-point2.first; x0=x0*x0;
	double x1=point1.second-point2.second; x1=x1*x1;
	return cellSize*sqrt(x1+x0);
	}

//grasshopper interaction

bool isAround(double have, double comparewith)
	{
	/// Tests whether two physical lengths differ by at most two cell widths,
	/// which is the compact support of the smeared radial delta function.
	if(abs(have-comparewith)/cellSize<=2) return true;
	else return false;
	}

/// Grasshopper interaction contribution using the globally selected deltaOption
/// The inputs are the distance between two points and the interaction distance (in any order)
double contributionEnergy(double have, double comparewith)
	{
	double contribution=0;

    if(isAround(have,comparewith))
        {
        if(deltaOption==0) contribution=(1. + cos(PI*(have-comparewith)/cellSize/2.))/4.;
        else if(deltaOption==1)
            {
			double absdist=abs(have-comparewith)/cellSize;
            if(absdist<1) contribution=17./48.+sqrt(3.)*PI/108.+absdist/4.-absdist*absdist/4.+(1-2*absdist)*sqrt(1.+12*absdist*(1-absdist))/16.-sqrt(3.)*asin(sqrt(3.)*(2*absdist-1)/2.)/12.;
            else if( (absdist>=1)&&(absdist<2) ) contribution=55./48.-sqrt(3.)*PI/108.-13.*absdist/12.+absdist*absdist/4.+(2*absdist-3)*sqrt(36*absdist-23.-12*absdist*absdist)/48.+sqrt(3.)*asin(sqrt(3.)*(2*absdist-3)/2.)/36.;
            }
        else throw logic_error("Error: Invalid delta function discretization option");
        }

	return contribution;
	}

// interaction fields

void validateInteractionTableReach(double distance){
	// The neighbor table is generated by shifting offsets obtained from a central
    // template. The grid must therefore extend far enough in both directions to
    // contain every lattice displacement with nonzero contributionEnergy
    // (|r-d| < 2*cellSize).
    const unsigned int templateReachCells = (gridSize - 1) / 2;
    const double requiredReachCells = std::ceil(distance / cellSize) + 1.0;
    if (static_cast<double>(templateReachCells) < requiredReachCells) {
        throw invalid_argument("Grid size is too small for the requested interaction-distance support.");
	}
}

GrasshopperInteractionTable buildInteractionTable(double distance){

	validateInteractionTableReach(distance);

	vector< pair<int,double> > dNeighbourTemplate;
	GrasshopperInteractionTable dNeighbourTable(gridArea);	//for each grid point: list of points that are its d-neighbours with corresponding energies

	// first build the template around the grid center
	// it contains the coordinate of all grid cells that can interact with the center point and the corresponding interaction contributions
    int center = (gridSize/2) * gridSize + gridSize/2;
    double thisEnergyContribution;
    pair<double,double> currentPosition=findPosition(center);
    for(unsigned int j=0;j<gridArea;j++)
        {
        thisEnergyContribution=contributionEnergy(distance,euclideanDistance(currentPosition,findPosition(j)));
        pair<int,double> thisPair(j,thisEnergyContribution);
        if(thisEnergyContribution > EPS) dNeighbourTemplate.push_back(thisPair);
        }

	// translate the template from the grid center to each grid site, taking into account the grid boundary
    const int signedGridSize = static_cast<int>(gridSize);
	for(unsigned int j=0;j<dNeighbourTemplate.size();j++)
		{
        int coord = dNeighbourTemplate[j].first;
        int relx = xcoord(coord) - signedGridSize/2;
        int rely = ycoord(coord) - signedGridSize/2;
        double relativeEnergy = dNeighbourTemplate[j].second;
        for(unsigned int i=0;i<gridArea;i++)
            {
            int gridLocationx = xcoord(i) + relx;
            int gridLocationy = ycoord(i) + rely;
            if(gridLocationx >= 0 && gridLocationy >= 0 && gridLocationx < signedGridSize && gridLocationy < signedGridSize)
                {
                pair<int,double> thisPair(gridLocationx + gridLocationy*gridSize, relativeEnergy);
                dNeighbourTable[i].push_back(thisPair);
                }
            }
		}

	return dNeighbourTable;
}

std::vector<double> buildGrasshopperInteractionGrid(const unsigned char grid[], const GrasshopperInteractionTable& table){

	// this table keeps track of grasshopper energy contributions of each grid point for the current configuration
	// specifically, interactionGrid[i] = sum_j s_j w(i,j) for every grid site i, including empty sites
	std::vector<double> interactionGrid(gridArea);
	for(unsigned int i=0;i<gridArea;i++)
		{
		interactionGrid[i]=0;
		for(unsigned int j=0;j<table[i].size();j++)
			{
			if(grid[table[i][j].first]==true)
				{interactionGrid[i] += table[i][j].second;}
			}
		}
	return interactionGrid;

}

double totalGrasshopperInteraction(const unsigned char grid[], const std::vector<double>& interactionGrid){

	double energy = 0.0;
	for (unsigned int i=0; i<gridArea; i++)
		if (grid[i])
			energy += interactionGrid[i];

	return energy / 2.0;

}

//nearest-neighbor contributions
unsigned int nearestNeighborCount(const unsigned int cell, const unsigned char grid[]){
	unsigned int NNenergy = 0;
	const int signedGridSize = static_cast<int>(gridSize);

	//down
	if(cell>=gridSize) NNenergy += grid[cell-gridSize];
	//up
	if(cell<gridSize*(gridSize-1)) NNenergy += grid[cell+gridSize];

	int gridLocationx = xcoord(cell);
	//left
	if(gridLocationx != 0) NNenergy += grid[cell-1];
	//right
	if(gridLocationx != signedGridSize-1) NNenergy += grid[cell+1];

	return NNenergy;
}

bool areNearestNeighbors(const unsigned int cell1, const unsigned int cell2){

	const unsigned int dx = xcoord(cell1) > xcoord(cell2) ? xcoord(cell1)-xcoord(cell2) : xcoord(cell2)-xcoord(cell1);
    const unsigned int dy = ycoord(cell1) > ycoord(cell2) ? ycoord(cell1)-ycoord(cell2) : ycoord(cell2)-ycoord(cell1);

	return dx + dy == 1;
}

int nearestNeighborBondDifference(const unsigned int oldCell, const unsigned int newCell, const unsigned char grid[]){
	// if old and new cell are nearest neighbors, need to account for old cell emptying after the move
	return static_cast<int>(nearestNeighborCount(newCell, grid)) - static_cast<int>(nearestNeighborCount(oldCell, grid)) - areNearestNeighbors(oldCell, newCell);
}

//normalizations
double normalizeGrasshopperEnergy(double energy, double distance){
	// energy counts each occupied pair once; P_G = energy / (pi * distance * N^(3/2))
    const double sqrtN = sqrt(static_cast<double>(totalNumSpins));
    return energy / (PI * distance * totalNumSpins * sqrtN);
}

double normalizeGrasshopperInteraction(double interaction, double distance){
    const double sqrtN = sqrt(static_cast<double>(totalNumSpins));
    return interaction / (2.0 * PI * distance * sqrtN);
}

double normalizeNearestNeighborCount(unsigned int count){
    return static_cast<double>(count) / 4.0;
}

double nearestNeighborProbability(long long nearestNeighborBonds){
    return static_cast<double>(nearestNeighborBonds) / (2.0 * totalNumSpins);
}
