#include "utilities.hpp"
#include "setup.hpp"
#include "annealing.hpp"
#include "simulation_parameters.hpp"

unsigned int totalNumSpins;
double cellSize;
unsigned int gridSize;
unsigned int gridArea;
double tempScaling;
int deltaOption;

using namespace std; 

int main(int inputN,char *inputV[]) {
    try {
    
    // SETUP -------------------------------------------------------------------------------------
	
    // read parameters from command-line arguments and define derived quantities

    const SimulationParameters parameters = parseSimulationParameters(inputN, inputV);
    const double d = parameters.hoppingDistance;
    totalNumSpins = parameters.totalNumSpins;
    cellSize=1./sqrt(double(totalNumSpins));

    if (parameters.gridSize.has_value()) {
        gridSize = *parameters.gridSize;
    }
    else {
        const double automaticHalfGridSize =
            sqrt(double(totalNumSpins)) + 3*d/cellSize + EPS;
        if (!isfinite(automaticHalfGridSize)
            || automaticHalfGridSize > numeric_limits<int>::max()) {
            throw invalid_argument("Automatically selected grid size is outside the supported range.");
        }
        gridSize=2*static_cast<unsigned int>(static_cast<int>(automaticHalfGridSize));
    }

    const unsigned long long selectedGridArea =
        static_cast<unsigned long long>(gridSize) * gridSize;
    if (selectedGridArea > numeric_limits<unsigned int>::max()) {
        throw invalid_argument("Grid area is outside the supported range.");
    }
    if (static_cast<unsigned long long>(totalNumSpins) >= selectedGridArea) {
        throw invalid_argument("N must be smaller than the grid area.");
    }
    gridArea = static_cast<unsigned int>(selectedGridArea);

    // The neighbor table is generated by shifting offsets obtained from a central
    // template. The grid must therefore extend far enough in both directions to
    // contain every lattice displacement with nonzero contributionEnergy
    // (|r-d| < 2*cellSize).
    const unsigned int templateReachCells = (gridSize - 1) / 2;
    const double requiredReachCells = std::ceil(d / cellSize) + 1.0;
    if (static_cast<double>(templateReachCells) < requiredReachCells) {
        throw invalid_argument("Grid size is too small for the hopping-distance support.");
    }
    
    double maxtime=parameters.hours;
    maxtime=60*60*maxtime*1000;
    
    long unsigned int maxsteps=parameters.maxSteps;
    
	long unsigned int temproundsteps=parameters.temperatureRoundSteps.value_or(0UL);
    if(temproundsteps>maxsteps) temproundsteps=int(maxsteps/1000.);
    if(temproundsteps<10) temproundsteps=totalNumSpins;
    
	double temperature=parameters.initialTemperature;
	double finaltemperature=parameters.finalTemperature;
    
    int numberannealingsteps=parameters.annealingSteps;
    tempScaling=pow((finaltemperature/temperature),1./double(numberannealingsteps));
    int configOutputs = parameters.configurationOutputs; // maximal number of configuration snapshots to save for animation
    int outputconfigbeforetherm=numberannealingsteps/100; int annealingcounter=0;
	
    string initconf=parameters.initialConfiguration;
    deltaOption=parameters.deltaOption;

    double NNint = parameters.nearestNeighborInteraction;
    
    // one factor of 1/2 is already taken care of by avoiding double counting
    double probabilityNormFactor = 1/PI/d/pow(double(totalNumSpins),3./2.);
    
	gsl_rng * RNG = gsl_rng_alloc (gsl_rng_mt19937);
    long unsigned int seed=parameters.randomSeed.value_or(0UL);
    // Use system clock if no random seed supplied (seed is always output)
    if(seed < EPS) seed=chrono::duration_cast<chrono::seconds>(chrono::system_clock::now().time_since_epoch()).count();
	gsl_rng_set (RNG, seed);

    ofstream result("result.dat");
	
	unsigned int temproundcounter=0;
	double accratio;
    long unsigned int counter=0; long accepted=0; long accepted_current=0;
    
    result << "2D Grasshopper with Simulated Annealing, Euclidean metric\n\n"
           << "Total number of spins: " << totalNumSpins << '\n'
           << "Hopping distance: " << d << '\n'
           << "Nearest Neighbor interaction coefficient: " << NNint << '\n'
           << "Size of grid: " << gridSize << '\n'
           << "Size of cell: " << cellSize << "\n\n"
	       << "Random seed: " << seed << '\n'
           << "Option for delta-function discretization: " << deltaOption << '\n'
	       << "Initial temperature: " << temperature << '\n'
	       << "Final temperature: " << finaltemperature << '\n'
	       << "Temperature scaling factor: " << tempScaling << '\n'
	       << "Number of annealing steps: " << numberannealingsteps << '\n'
	       << "Initial number of steps before temperature scaling: " << temproundsteps << "\n\n";

    auto begin = chrono::high_resolution_clock::now();
    
    // CONSTRUCT NEIGHBOR LIST ---------------------------------------------------------------------------  

    vector< pair<int,double> > dNeighbourTemplate;
	std::vector<std::vector<std::pair<int,double>>> dNeighbourTable(gridArea);	//for each grid point: list of points that are its d-neighbours with corresponding energies
    
    int center = (gridSize/2) * gridSize + gridSize/2;
    double thisEnergyContribution;
    pair<double,double> currentPosition=findPosition(center);
    for(unsigned int j=0;j<gridArea;j++)
        {
        thisEnergyContribution=contributionEnergy(d,euclideanDistance(currentPosition,findPosition(j)));
        pair<int,double> thisPair(j,thisEnergyContribution);
        if(thisEnergyContribution > EPS) dNeighbourTemplate.push_back(thisPair);
        }
    
	for(unsigned int j=0;j<dNeighbourTemplate.size();j++)
		{
        int coord = dNeighbourTemplate[j].first;
        int relx = xcoord(coord) - gridSize/2;
        int rely = ycoord(coord) - gridSize/2;
        double relativeEnergy = dNeighbourTemplate[j].second;
        for(unsigned int i=0;i<gridArea;i++)
            {
            int gridLocationx = xcoord(i) + relx;
            int gridLocationy = ycoord(i) + rely;
            if(gridLocationx >= 0 && gridLocationy >= 0 && gridLocationx < gridSize && gridLocationy < gridSize)
                {
                pair<int,double> thisPair(gridLocationx + gridLocationy*gridSize, relativeEnergy);
                dNeighbourTable[i].push_back(thisPair);
                }
            }
		}
		
    auto now = chrono::high_resolution_clock::now();
    auto timeDiff = chrono::duration_cast<chrono::milliseconds>(now-begin).count();
	result << "Time to construct neighbors list: " << timeDiff << "ms" << endl;
    
    // INITIAL SPIN CONFIGURATION ------------------------------------------------------------------------
    
    std::vector<unsigned char> grid(gridArea);          //true if spin=1 at this grid point
    std::vector<double> energyGrid(gridArea);
	std::vector<int> spinArray(totalNumSpins);          //grid point where any spin is
	std::vector<int> noSpinArray(gridArea-totalNumSpins); //complementary to above: grid point where no spin is
    
    initialize(grid.data(), spinArray.data(), RNG, initconf);
    
    unsigned int noSpinCounter=0;
    double energy = 0;
    double NNenergy = 0;
	for(unsigned int i=0;i<gridArea;i++)
		{
		if(grid[i]==false) {noSpinArray[noSpinCounter]=i; noSpinCounter++;}
		// NN contributions
		else {
            //down
            if(i>=gridSize) NNenergy += grid[i-gridSize];
            //up
            if(i<gridSize*(gridSize-1)) NNenergy += grid[i+gridSize];
            
            int gridLocationx = xcoord(i);
            //left
            if(gridLocationx != 0) NNenergy += grid[i-1];
            //right
            if(gridLocationx != gridSize-1) NNenergy += grid[i+1];
            }
        // Fill the energy grid
        energyGrid[i]=0;
        for(unsigned int j=0;j<dNeighbourTable[i].size();j++)
			{
			if(grid[dNeighbourTable[i][j].first]==true)
				{energyGrid[i] += dNeighbourTable[i][j].second;}
			}
        if(grid[i]==true) energy += energyGrid[i];
		}
    energy = energy/2.;
    NNenergy = NNenergy*NNint/2.;
    energy += NNenergy;
		
    int bufferLimit = 10000;
    int flushInterval = 60*1000;
    BufferedFileWriter energies("energies.dat", bufferLimit, chrono::milliseconds(flushInterval));
	energies.write(to_string(energy*probabilityNormFactor));
    BufferedFileWriter temperatures("temperatures.dat", bufferLimit, chrono::milliseconds(flushInterval));
	ofstream configuration("config.dat");
	if(configOutputs > 0)
        {
        ostringstream buffer;
        for(unsigned int i=0;i<totalNumSpins;i++) buffer << spinArray[i] << " ";
        buffer << energy*probabilityNormFactor << endl;
        configuration << buffer.str();
        }
    
	std::vector<int> bestSpinArray(totalNumSpins);  //the overall best spin array during the whole run
	for(unsigned int i=0;i<totalNumSpins;i++) bestSpinArray[i]=spinArray[i];
	double bestenergy=energy;
		
    // MAIN LOOP ------------------------------------------------------------------------------------------
		
    while( (timeDiff<maxtime) && (counter<maxsteps) )
        {
		counter++; temproundcounter++;
		
        // MC update
		int destroy=gsl_rng_uniform_int (RNG, totalNumSpins);
		int oldSpinCoord=spinArray[destroy];
		int create=gsl_rng_uniform_int (RNG, gridArea-totalNumSpins);
		int newSpinCoord=noSpinArray[create];
		
		double energyDifference=energyGrid[newSpinCoord]-energyGrid[oldSpinCoord];
        if(isAround(d,euclideanDistance(findPosition(newSpinCoord),findPosition(oldSpinCoord))))//NOTE more efficient to keep this check explicit
            {
            energyDifference -= contributionEnergy(d,euclideanDistance( findPosition(newSpinCoord),findPosition(oldSpinCoord) ));
            }
        // Nearest neighbor contributions
        if(abs(NNint) > EPS)
            {
            //down
            if(newSpinCoord>=gridSize && newSpinCoord-gridSize != oldSpinCoord) energyDifference += NNint*grid[newSpinCoord-gridSize];
            if(oldSpinCoord>=gridSize && oldSpinCoord-gridSize != newSpinCoord) energyDifference -= NNint*grid[oldSpinCoord-gridSize];
            //up
            if(newSpinCoord<gridSize*(gridSize-1) && newSpinCoord+gridSize != oldSpinCoord) energyDifference += NNint*grid[newSpinCoord+gridSize];
            if(oldSpinCoord<gridSize*(gridSize-1) && oldSpinCoord+gridSize != newSpinCoord) energyDifference -= NNint*grid[oldSpinCoord+gridSize];
                
            int gridLocationx = xcoord(newSpinCoord);
            //left
            if(gridLocationx != 0 && newSpinCoord-1 != oldSpinCoord) energyDifference += NNint*grid[newSpinCoord-1];
            //right
            if(gridLocationx != gridSize-1 && newSpinCoord+1 != oldSpinCoord) energyDifference += NNint*grid[newSpinCoord+1];
            gridLocationx = xcoord(oldSpinCoord);
            //left
            if(gridLocationx != 0 && oldSpinCoord-1 != newSpinCoord) energyDifference -= NNint*grid[oldSpinCoord-1];
            //right
            if(gridLocationx != gridSize-1 && oldSpinCoord+1 != newSpinCoord) energyDifference -= NNint*grid[oldSpinCoord+1];
            }

		bool accept;
		if(energyDifference>=0) accept=true;
		else accept=acceptreject(energyDecreaseProbDistr(energyDifference,temperature),RNG);
		
		if(accept==true)
			{
			grid[oldSpinCoord]=false; grid[newSpinCoord]=true;
			spinArray[destroy]=newSpinCoord; noSpinArray[create]=oldSpinCoord;
			energy+=energyDifference;
            //update energy grid
            for(unsigned int j=0;j<dNeighbourTable[oldSpinCoord].size();j++)
                {
                energyGrid[dNeighbourTable[oldSpinCoord][j].first] -= dNeighbourTable[oldSpinCoord][j].second;
                }
            for(unsigned int j=0;j<dNeighbourTable[newSpinCoord].size();j++)
                {
				energyGrid[dNeighbourTable[newSpinCoord][j].first] += dNeighbourTable[newSpinCoord][j].second;
                }
			accepted_current++;
			if(energy>bestenergy)
				{
                bestenergy=energy; 
                for(unsigned int i=0;i<totalNumSpins;i++) bestSpinArray[i]=spinArray[i];
                }
			}
        
        // cooling step
		if(temproundcounter==temproundsteps)
			{
			if(temperature>finaltemperature) 
				{
				temperature=temperatureDecrease(temperature);
				if(annealingcounter%outputconfigbeforetherm==0 && configOutputs > 0) 
					{
                    ostringstream buffer;
                    for(unsigned int i=0;i<totalNumSpins;i++) buffer << spinArray[i] << " ";
                    buffer << energy*probabilityNormFactor << endl;
                    configuration << buffer.str();
                    }
				annealingcounter++;
				}
			else if(annealingcounter<configOutputs)
				{
				annealingcounter++; 
                ostringstream buffer;
                for(unsigned int i=0;i<totalNumSpins;i++) buffer << spinArray[i] << " ";
                buffer << energy*probabilityNormFactor << endl;
                configuration << buffer.str();
				}
			accratio=accepted_current/double(temproundcounter);
            temperatures.write(to_string(counter) + '\t' + to_string(temperature) + '\t' + to_string(accratio));
			energies.write(to_string(energy*probabilityNormFactor));
			accepted+=accepted_current; accepted_current=0;
			temproundcounter=0;
			temproundsteps=stepIncrease(temproundsteps);
			}
		
		now = chrono::high_resolution_clock::now();
		timeDiff = chrono::duration_cast<chrono::milliseconds>(now-begin).count();
		}
		
    // WRAP UP --------------------------------------------------------------------------------------------
    
    temperatures.flush();
    energies.flush();
    
	result << "\nSimulation took " << timeDiff/60./1000 << " minutes" << '\n'
	       << "Finished after " << counter << " steps" << '\n'
	       << "Final temperature: " << temperature << '\n'
	       << "Average acceptance ratio: " << accepted/double(counter) << "\n\n"
	       << "final energy: " << energy << '\n'
	       << "best energy: " << bestenergy << '\n'
           << "final probability: " << energy*probabilityNormFactor << '\n'
           << "best probability: " << bestenergy*probabilityNormFactor << "\n\n";
    
    if(configOutputs==0) {remove("config.dat");}
    saveConfig(spinArray.data(), "finconf.dat");
    saveConfig(bestSpinArray.data(), "bestconf.dat");
    
    return 0;
    }
    catch (const exception& error) {
        cerr << "Error: " << error.what() << endl;
        return 1;
    }
}
